name: build-release-windows

on:
  push:
    tags:
      - '*'

concurrency:
  group: build-release-windows
  cancel-in-progress: false

jobs:
  build-windows:
    runs-on: windows-2025
    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: false
          pacboy: gcc:p cmake:p ninja:p make:p

      - name: Restore vcpkg cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-release-windows-x64-${{ hashFiles('desktop/vcpkg.json') }}
          restore-keys: vcpkg-release-windows-x64-

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: desktop/vcpkg.json

      - name: Configure
        run: |
          cmake --preset release-mingw \
            -DCMAKE_MAKE_PROGRAM="$MINGW_PREFIX/bin/ninja.exe" \
            -DCMAKE_C_COMPILER="$MINGW_PREFIX/bin/gcc.exe" \
            -DCMAKE_CXX_COMPILER="$MINGW_PREFIX/bin/g++.exe"
        working-directory: desktop

      - name: Build
        run: cmake --build --preset release-mingw
        working-directory: desktop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pocketwalker-windows-x86_64
          path: desktop/build/release-mingw/release/pocketwalker.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "pocketwalker ${{ github.ref_name }}"
          files: desktop/build/release/release/pocketwalker.exe
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save vcpkg cache
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-release-windows-x64-${{ hashFiles('desktop/vcpkg.json') }}